### ISSUE TITLE
Fail to create `kind` kubernetes cluster

### ISSUE THREAD

**Issue by caniko** [damentz/liquorix-package#101]
[Link](https://github.com/kubernetes-sigs/kind/issues/2852) to issue on the `kind` repository.

I was on the `bmq` kernel, garuda linux (downstream from arch).

**Comment by damentz** [comment]
Hey @caniko, this is a known issue.  Many of the CPU cgroup properties are missing with Project-C alternative schedulers.  A similar issue is open already for Pterodactyl since it needs these tunables to operate properly: https://github.com/damentz/liquorix-package/issues/82

And here's the upstream issue reported to Project-C: https://gitlab.com/alfredchen/linux-prjc/-/issues/51

Marking this as duplicate and closing.

**Comment by caniko** [comment]
Wow, very insightful, thank you.

**Comment by vinibali** [comment]
I just have the same problem, do we know that cgroups v2 implementation is missing from the scheduler?

**Comment by damentz** [comment]
This issue is now resolved with stubs that were added recently to Liquorix.

**Comment by damentz** [comment]
Marking properly as resolved.
