### ISSUE TITLE
Two or three kernels per LTS realise, CONFIG_X86_SPEEDSTEP_CENTRINO=m for phc-intel

### ISSUE THREAD

**Issue by Aalexeey** [damentz/liquorix-package#115]
Hi,
Can You build liquorix kernel on top of a LTS kernels, occasionally? The new kernels can't be used with current repos due to often dkms modules incompability, Virtul Box, NVidia etc. will build successfully with current distro kernel. I use old 5.10.0-17.1-liquorix with chimaera/bullseye on some PSs, can't use others.
Can CONFIG_X86_SPEEDSTEP_CENTRINO=m be included to be able to run phc-intel? 
https://gitlab.com/linux-phc/phc-intel

**Comment by damentz** [comment]
Hi @Aalexeey, there's no plans to release an LTS kernel.  If there's a problem with the current kernel, I suggest you submit an issue so someone can help.

As for the speedstep centrino driver, here's what the Kconfig says:

```
CONFIG_X86_SPEEDSTEP_CENTRINO:

This is deprecated and this functionality is now merged into
acpi_cpufreq (X86_ACPI_CPUFREQ). Use that driver instead of
speedstep_centrino.
This adds the CPUFreq driver for Enhanced SpeedStep enabled
mobile CPUs.  This means Intel Pentium M (Centrino) CPUs
or 64bit enabled Intel Xeons.

To compile this driver as a module, choose M here: the
module will be called speedstep-centrino.

For details, take a look at <file:Documentation/cpu-freq/>.

If in doubt, say N.
```

Enabling this module will only cause problems if it accidentally takes over in acpi-cpufreq's stead.  Also, Liquorix is overall a power hungry kernel.  Its tick rate is higher and the options for low power modes are reduced (no schedutil, no powersave modes), since the intention is maximum performance.  If you desire a kernel that will get you extra battery life, I recommend sticking with stock.

EDIT: I missed the first part about DKMS.  If you need a lot of out-of-tree modules, as long as you're running an Arch based distribution you should be fine.  Frozen pool distributions should be avoided when running a modern custom kernel since the firmware and dkms packages will often not be compatible with any recent version of Liquorix.
