### ISSUE TITLE
Support for Arm64 architecture on Ubuntu 22.04

### ISSUE THREAD

**Issue by serialpotato** [damentz/liquorix-package#128]
Hi. Can we have the arm64 release of this kernel? If not, can you please provide details if this kernel can be compiled for arm64 on ubuntu OS 22.04?

**Comment by damentz** [comment]
Liquorix is only provided officially for architectures that I use myself.  Since I don't use ARM on consumer electronics, the only way I'd support a fork of Liquorix for ARM is if I was paid through contract or salary since the time required and testing needed would be outsized to the number of users of it.

As for the viability of ARM, existing consumer hardware isn't powerful enough to really take advantage of Liquorix, and for cases where the hardware is powerful, is typically in server and appliance type setups that don't need it.  Not to mention, the more powerful systems are big.LITTLE, which aren't supported by PDS in a way that the hardware can be utilized effectively.

You can see my original post here that briefly touched on it: https://github.com/damentz/liquorix-package/issues/65.  With that all said, there probably won't be an official fork of Liquorix for ARM64 for some time.

**Comment by salvalie** [comment]
Hopefully you decide to try out an rk3588. It's  very decent for its price. Way more caoable than your old pinebook pro. Also, since we have box64 and fex emulators we are very decent platform for lightweight x86_64 gaming. I did test minecraft v1.21 vanilla and was very decent on a mid range mediatek with 4 gigs of ram and without vulkan drivers ready as today (unlike rk3588).
