### ISSUE TITLE
4.20.0-13.1: CPU frequency scaling doesn't work

### ISSUE THREAD

**Issue by Lastique** [damentz/liquorix-package#13]
Regardless of the CPU load, its frequency always stays locked at 1.6 GHz, whereas it should normally scale up to the max frequency set in UEFI.

Kernel version:
```
Linux 4.20.0-13.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 4.20-11ubuntu1~cosmic (2019-02-28)
```

The system is Kubuntu 18.10, the kernel is installed from the official PPA.

CPU:
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      : Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
stepping        : 7
microcode       : 0x2e
cpu MHz         : 1600.007
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 6800.01
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:
```

```
$ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
powersave
$ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
conservative userspace powersave ondemand performance schedutil 
```

**Comment by Lastique** [comment]
I can add that I have the "powersave" governor enabled for the stock generic Ubuntu kernel and frequency scaling works as intended there.

**Comment by damentz** [comment]
Hi @Lastique 

The *powersave* governor with cpufreq selects the lowest frequency advertised through acpi-cpufreq:

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/Documentation/admin-guide/pm/cpufreq.rst?h=v4.20.14#n364

Ubuntu's kernel enables the pstates frequency governor, and *powersave* is synonymous with *ondemand*:

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/Documentation/admin-guide/pm/intel_pstate.rst?h=v4.20.14#n77

If you want to run Liquorix, you'll want to adjust your configuration accordingly.  Or rather, powersave _should_ be the default for Intel P-State on Ubuntu, and ondemand _is_ the default on Liquorix.  So by overriding what your distribution sets, you will get the same behavior between Liquorix and Ubuntu stock.

**Comment by Lastique** [comment]
Thanks for your reply. So, if I understood correctly, Liquorix doesn't support intel_pstate and therefore `powersave` has a different meaning there, correct? Is there a reason why intel_pstate is not supported?

PS: I'm not sure what the difference between `ondemand` and intel_pstate `powersave` is, but I would guess the latter is somewhat more optimal due to employing Intel-specific CPU features. Wouldn't that make `ondemand` not an equivalent replacement?

**Comment by damentz** [comment]
In my own testing and with some benchmarks Phoronix has released, I don't see a specific advantage to including Intel P-State.  It also helps that in the `ondemand` and `performance` governors for acpi-cpufreq, both have a switch for boost that's enabled by default.  This gives you access to all the extra TDP overhead that Intel builds into their chips that I think pstate was originally developed for.

Another purpose of pstate is to take advantage of grouping tasks on to individual cores to take advantage of high single core boosts.  Since MuQSS is traditionally really bad at keep tasks contained to a single core, pstate won't improve performance or balance cpu frequencies any better than ondemand.

**Comment by damentz** [comment]
I may add Intel P-State in the future, but it needs to be worth it to maintain the configurations of two frequency governors with MuQSS more spread out method of scheduling.

I'm closing this issue, but if you have any more questions I should see it in my unread github notifications.

**Comment by melvyn2** [comment]
The problem with disabling `intel_pstate` is that suddenly my max _reported_ frequency is bumped down from 5 GHz to 3.6 GHz. This causes issues with certain apps I use the control my CPU clock, and ends up reducing my perfomance. Simply reenabling the driver fixes the issue.
This might not be important enough to warrant anything, but I did want to make sure that you were aware.

**Comment by damentz** [comment]
A lot has changed since this issue was opened.  Here's the current status for record:

1. Intel P-State is now compiled as a module into the kernel
2. Intel P-State is disabled by default, but can be enabled as default by passing `intel_pstate=enable` into kernel boot parameters.
3. Of `acpi-cpufreq` modules, both `powersave` and `conservative` were disabled (powersave disabled because Intel P-State systems would choose powersave and destroy performance by accident).

This problem shouldn't be an issue anymore, if it is, try adding `intel_pstate=enable` to your boot parameters.  Just be aware that `intel_pstate` does an abysmal job selecting the right CPU frequency while the system is under load, so you will get worse performance on light and medium system loads than compared to `ondemand` with `acpi-cpufreq`.

EDIT: Here's the commit in 5.7/zen-sauce that supports enabling `intel_pstate` after it's been disabled via kernel boot parameter: https://github.com/zen-kernel/zen-kernel/commit/761a73ae94d9f17373c0dda1cacdb502a2d766cc

**Comment by melvyn2** [comment]
Ah, thanks for the explanation. I re-enabled `intel_pstate` by removing the argument during the build process, though just adding the kernel arg would have been simpler. 
With either `ondemand` or `performance` when I had `intel_pstate` disabled, `/sys/bus/cpu/devices/cpu*/cpufreq/cpuinfo_cur_freq` reported the 3.6 GHz I was talking about earlier, and so I assumed that this was causing lower performance. However, this might have been a bug - I'm not sure. I might try switching back to `ondemand` without `intel_pstate` later.
