### ISSUE TITLE
PSI disabled but required for Waydroid

### ISSUE THREAD

**Issue by baanan** [damentz/liquorix-package#130]
I am having the same problem [here](https://github.com/waydroid/waydroid/issues/136), but PSI is unsupported since 081b53222d5b1cfa2cddd6e1b1edf1896ac61a10. I would be completely fine with changing the config and building the kernel myself, but I don't exactly know how to do that.

**Comment by damentz** [comment]
Hi @ThatEpicBanana, since I disabled that configuration, the maintainer of Project-C explicitly disabled support for PSI: https://gitlab.com/alfredchen/linux-prjc/-/commit/542887ccaeadc65843ec171bccc87f8aa8bbca95

Basically, there's too many subtle bugs people were hitting with it enabled, so the maintainer opted to disable it entirely since his issue page was getting flooded with bugs caused by this feature.

I recommend opening a new issue with Waydroid (that issue is closed), since enabling PSI worked around some bug in the project itself.  Most likely some bad memory configuration that PSI allowed an OOM daemon to properly kill the right process for on low memory systems.

**Comment by damentz** [comment]
It also appears that someone else has asked this question of why PSI is required, it seems to be something the community has decided is mandatory but the developers have said nothing about it: https://github.com/waydroid/waydroid/issues/783

**Comment by baanan** [comment]
Looking into it, dmesg is complaining about the [Low Memory Killer Daemon](https://source.android.com/docs/core/perf/lmkd) which actually does use PSI under the hood.

**Comment by baanan** [comment]
I've confirmed that this is the problem, dmesg complains `init: critical process 'lmkd' exited 4 times before boot completed`, and the binder dies. I've tried setting `ro.lmk.use_psi=false` in `/var/lib/waydroid/waydroid_base.prop`, but that didn't fix the issue.
