### ISSUE TITLE
Regarding adding "schedutil"

### ISSUE THREAD

**Issue by Ravi-Kishor** [damentz/liquorix-package#138]
please add "schedutil" cpu governer too...its too useful in saving batter on laptops, I use auto-cpufreq tool from github to auto switch scheduler, so having schedutil will be a great thing. please consider this in nect update.

![image](https://github.com/damentz/liquorix-package/assets/97280268/ff05ba21-429c-4f21-b6e7-c0de11c6374e)

**Comment by damentz** [comment]
**schedutil** was removed from Liquorix due to massive performance issues that were discovered during Phoronix testing.  Not only does it have a bad interaction with PDS/MuQSS, but its focus on efficiency defeats the purpose of Liquorix.

Now you may be asking, why not leave it as an option?  The answer is it _was_ an option and the default is **performance**.  The problem is most distributions configure their cpufreq daemons to force **schedutil** if they see it, degrading the experience running Liquorix.  The fix is to obviously just remove it since not only is it a bad fit for Liquorix, but when a distribution overrides the governor to **schedutil**, the kernel performs worse than stock.

I recommend using **ondemand**, you'll get the battery life you're looking for and performance at the same time.

**Comment by Rongronggg9** [comment]
Try intel_pstate (I assume your laptop uses an Intel CPU) if you do need something "works like" schedutil. Note that Liquorix has it disabled by default.

FYI: https://www.kernel.org/doc/html/v4.19/admin-guide/pm/intel_pstate.html
