### ISSUE TITLE
6.5-9 awesome but need 5.19

### ISSUE THREAD

**Issue by juanpc2018** [damentz/liquorix-package#145]
paragon Universal APFS / HFS+ FUSE drivers require Kernel 5.19 maximum.

rapiddisk probably also requires older kernel.
Marvell Aquantia AQ100 SFP+ drivers, etc...

https://liquorix.net/sources/
https://github.com/zen-kernel/zen-kernel/releases?page=19

for backward compatibility, older versions should be available in aptitude PPA.
Grub2 & rEFInd can Boot Multi Kernel.

**Comment by damentz** [comment]
Old kernels are not supported.  You will need to stick with an old distribution or stock kernel if you have a particular need for those devices and filesystems.

**Comment by juanpc2018** [comment]
Problem is:
22.04 its an [LTS](https://wiki.ubuntu.com/LTS) release,
23.10 Mantic is Not an LTS release.
https://en.wikipedia.org/wiki/Ubuntu_version_history#Table_of_versions
22.04 LTS support goes to 2027, security updates to 2032.
23.10 support goes to 2024.

**Comment by damentz** [comment]
You should never be running an LTS distribution with Liquorix unless it's the latest version of Ubuntu available.  The older user space will eventually cause unexplainable issues with the kernel.

Also, the "support" is a red herring, you will upgrade to 24.04, then 24.10, and so forth as they become available.  The support is meaningless in this context since you're staying up to date and receiving distribution "support" in perpetuity.

Ideally you should go the complete opposite direction you're suggesting and switch to a rolling release distribution such as Arch Linux.  Frozen pool distributions eventually cause issues like you're running into and are completely unsupportable.

**Comment by mckaygerhard** [comment]
this is ilogic you are suggesting to use unstable distros to play large games or things that can relly on bugs still not yet resolved?

there is any way to build older kernels from this repository? @damentz  ?
