### ISSUE TITLE
ZFS support?

### ISSUE THREAD

**Issue by Ticklezz** [damentz/liquorix-package#149]
Does the kernel support ZFS?

**Comment by damentz** [comment]
The more important question is if ZFS supports the major kernel that Liquorix running as.

Here's an article for OpenZFS 2.2 supporting 6.5: https://9to5linux.com/openzfs-2-2-released-with-linux-6-5-support-block-cloning-and-more

Looking through github issues, I only see an issue for v6.7-rc1, so you're fine for now but may not be when Liquorix switches to 6.7.

IMO, if you need ZFS support, I recommend running it on a NAS and sticking to filesystems supported in mainline for the system running the enthusiast kernel.  You may be able to get it working now but that's not guaranteed.  It's normal for ZFS to not be supported randomly since mainline can change their internal ABIs at any time for any reason.

**Comment by Ticklezz** [comment]
I'm running ZFS now and didn't want to run into an issue with Liquorix. So for now I will just not risk using the kernel and randomly break my system. Thank you for your reply.

**Comment by damentz** [comment]
That's fair, and yes, it is risky to run out-of-tree DKMS modules for filesystems, since you can easily lose access to your data if the DKMS module becomes incompatible with the next version of Linux.
