### ISSUE TITLE
Google BBRv3 for Liquorix

### ISSUE THREAD

**Issue by serialpotato** [damentz/liquorix-package#151]
Hi. Google has recently announced Google BBRv3 TCP Congestion Protocol:
https://www.phoronix.com/news/Google-BBRv3-Linux

I was wondering if we could expect the BBRv3 Congestion Protocol to be implemented in liquorix kernel as it has significant improvements over BBRv2 (currently used by liquorix) and is already included in 3rd party kernels such as xanmod. 

However, xanmod has its own set of problems and liquorix is the daily driver for many kernel enthusiasts as its more optimized and yields better performance. I really wish we are able to enjoy liquorix with this new feature.

Thanks

**Comment by damentz** [comment]
Liquorix has already been using BBRv3 since it was added to Zen Kernel:

- https://github.com/zen-kernel/zen-kernel/commits/6.6/bbr3
- https://github.com/zen-kernel/zen-kernel/commits/6.5/bbr3
- https://github.com/damentz/liquorix-package/commit/54b3c81e15264a3afd8c9f69caf6309cc4d09f84

It's not obvious that it's running because Google replaced the existing BBR congestion control in the kernel without changing the name.

I do see though that my website is out of date with this information, so I'll update that when I get some time.
