### ISSUE TITLE
initramfs-tools custom hook fails on liquorix kernel image

### ISSUE THREAD

**Issue by linuxazo** [damentz/liquorix-package#159]
Dear Maintainer,

I have a custom initramfs-tools hook on Debian which works on Debian stock kernel images, as well as on Xanmod.
However, my omit hook fails to delete/remove the amdgpu.ko or amdgpu.ko.xz kernel module from initrd image in case of Liquorix kernel image.

Please advise.  Thank You

Attached is the hook (/etc/initramfs-tools/hooks/omit):
[omit.zip](https://github.com/damentz/liquorix-package/files/14159400/omit.zip)

**Comment by damentz** [comment]
Can you show how it fails?  Any output, error lines, log files would be appreciated.

But looking at your script, I think I already see the problem.  Liquorix recently switched to Zstandard compression over XZ due to a bug that Debian no longer supports XZ compressed kernels in Trixie and beyond.  You need to also look for files ending in `.zst`.

Or rather, replace:

```shell
OMIT_DRIVERS="amdgpu.ko amdgpu.ko.xz"
```

With

```shell
OMIT_DRIVERS="amdgpu.ko amdgpu.ko.xz amdgpu.ko.zst"
```

EDIT: Ideally, you'd want to just look for any variation of extension after the `.ko` using a wildcard, compression technologies change every 5-10 years.

**Comment by linuxazo** [comment]
Dear Developer @damentz , yup, this is more than enough.
For newer Debian kernels, I use .xz, for Liquorix, I see it's .zst, and ultimately, as you proposed, it is better to use * wildcard for any and all cases.

Thank You so much!
