### ISSUE TITLE
Missing Module

### ISSUE THREAD

**Issue by NiffirgkcaJ** [damentz/liquorix-package#180]
Hello! I want to ask if the `binder` module is intentionally not being added to this? I checked that the Linux Zen Kernel had that, but this doesn't ship it and this is the only easy `zen-kernel` distribution for Debian/Ubuntu.

I don't want to impose or anything! I just want to know.

**Comment by damentz** [comment]
Hey @NiffirgkcaJ, looks like binder was disabled in October 2023 (https://github.com/damentz/liquorix-package/commit/19b2a13f50c11a53bc7a565bf3ee69dbc2aa4711) since Waydroid requires `PSI` enabled to work properly with it.  Unfortunately, PSI is incompatible with Project-C / PDS (https://github.com/damentz/liquorix-package/commit/081b53222d5b1cfa2cddd6e1b1edf1896ac61a10) and the Project-C developer hasn't revisited what it would take to re-enable support.

I'm hoping something has changed with Waydroid though.  The last time I investigated, its dependency on PSI seemed arbitrary and the developers of Waydroid didn't have an explanation either.

**Comment by NiffirgkcaJ** [comment]
I see! Thank you for explaining!
