### ISSUE TITLE
linux-liquorix (6.12-9) not available on launchpad

### ISSUE THREAD

**Issue by vincent1990** [damentz/liquorix-package#188]
Hi, good day! Hope you are well.

I just got excited about the new update only to find that it's not available on launchpad. Can it please be checked if there is an issue with the build? The last available release on launchpad is 6.12-7ubuntu1 instead of 6.12-9.

**Comment by damentz** [comment]
Hello, it looks like you're right.  At least one distribution on both Debian and Ubuntu are failing to build with the latest kernel.  However, the way it's failing is not obvious to me and I currently don't have time this week to figure out what's going on.

Hopefully a stable update fixes the issue, otherwise it'll be about a week before I can look into this.

**Comment by damentz** [comment]
Ok, looks like something in both Debian Sid and Ubuntu Plucky breaks kernel builds currently.  For now, the succeeding Debian builds were pushed (bookworm and trixie).

However, you said you're on Ubuntu.  Are you running Plucky?  It's scheduled to release in April, 4 months from now.  All the other Ubuntu builds succeeded so you would need to downgrade to 24.10 (oracular) to receive an update.  You can also try manually changing your sources to use that kernel with plucky, but there's a non zero chance it won't work for many reasons.

**Comment by damentz** [comment]
Issue appears to be related to this: https://bugs-devel.debian.org/cgi-bin/bugreport.cgi?bug=1090999

**Comment by vincent1990** [comment]
I am on noble 24.04. The issue seems to have been resolved. Thank you for the latest release  :)
