### ISSUE TITLE
[Question] Custom Kernel (Liquorix)

### ISSUE THREAD

**Issue by MikkelDK** [damentz/liquorix-package#22]
Hi, @damentz 

Is there some-way to possible convert (make) custom of liquorix function, just with LowLatency & 1000HZ as an example, without its 250HZ?

And the same method with less PRI - for example:
On htop/top, I see some programs has 1 PRI, and htop has 8 PRI.

Thank you.

**Comment by damentz** [comment]
Hmm, I'm not entirely sure what you're asking.  Are you asking if I can make an input that lets us choose the tick rate at boot?  That's a good idea since workstation users that need the high tick rate (realtime audio), will benefit overriding Liquorix's choice.

Another option is to make two packages, linux-liquorix and linux-liquorix-lowlatency, but I'll need to think a bit more about the right way to do that.

And as far as PRI goes, I think that's a side effect of MuQSS deciding what runs next, but you can modify that with `schedtool`.

**Comment by MikkelDK** [comment]
@damentz - It's because I did tried install your kernel > and modify to make "1000HZ Kernel" with LowLatency from config-liquorix-x-x.version (example)

But it wasn't the same after installed "custom kernel" after compiling with the config, from the installation of liquorix's kernel (Example).

I know, your kernel running 250HZ, but could be nice (as an option) - so it's possible to choose: 250HZ or 1000HZ of installation with Liquorix's kernel(+ LowLatency)

**Comment by damentz** [comment]
@MikkelDK I tried running 1000hz again with MuQSS + tickless idle and it looks like the previous time accounting bugs I ran into are gone.  This means cpu utilization is measured correctly in your favorite monitoring tools and cpufreq is given correct data to underclock the CPU during low load.

I'm not entirely sure when this was fixed, but the point is that it's fixed and now the default again for Liquorix.  We're not going to need a separate kernel.  If you're running Ubuntu, builds should be out in the next 2 hours on launchpad, otherwise you can pull the latest kernel from Debian binaries on liquorix.net or Arch's AUR as of now.

**Comment by mrc4tt** [comment]
Hi @damentz 

Seems the Kernel does "KERNEL PANIC" or somehow with Debian 10(Buster) version.
I don't have access to KVM, so I can't see, what it does saying :'/ 

It's just killing me off to trying "Connecting" to Putty, but CMD(Ping) works fine, with the contact.

**Comment by damentz** [comment]
> Hi @damentz
> 
> Seems the Kernel does "KERNEL PANIC" or somehow with Debian 10(Buster) version.
> I don't have access to KVM, so I can't see, what it does saying :'/
> 
> It's just killing me off to trying "Connecting" to Putty, but CMD(Ping) works fine, with the contact.

I don't recommend running Liquorix on a server unless you really know what you are doing, or if method to restore to a stock kernel relatively easy in-case an update borks your system.  The only quality assurance I perform is basic dogfooding on most/all of my devices (depending on how big the change is), and so far this update hasn't caused any issues for me (desktop, laptop, actual liquorix.net KVM virtualized server).

It might be something in the release candidate patches that caused an issue.  Good news though is 5.4 has soaked for quite a while now so I'll probably switch to the 5.4 kernel series before the end of the year.  In the meantime, since it seems like you're running a server configuration, I'd recommend switching back to your distribution's stock kernel, especially if it's virtualized.
