### ISSUE TITLE
Latest update kernel not booting

### ISSUE THREAD

**Issue by bubobih** [damentz/liquorix-package#29]
Hello latest update im stuck at booting

https://i.imgur.com/UMXvbJc.png

**Comment by bubobih** [comment]
After googling i find that add nosmt in grub and regenerate kernel fix a problem

**Comment by damentz** [comment]
Ok, thanks for the update.  Here's the changelog for the last update:

linux-liquorix (5.6-4) unstable; urgency=medium

  * merge MuQSS v0.200
  * enable tickless idle
  * switch tick rate from 250hz to 1000hz
  * enable CGROUP options RDMA and PIDS
  * enable Pressure Stall Information (CONFIG_PSI), disabled by default
  * update version to 5.6.0-10.2

 -- Steven Barrett <steven@liquorix.net>  Tue, 05 May 2020 17:29:52 -0500

It could be that the change back to tickless idle (due to fixes in MuQSS v0.199/0.200), may be causing issues with your system.

When you do get a chance, can you see if `nothreadirqs` also solves your boot issues?  My experience is that threaded IRQs cause issues on tickless idle systems, but not periodic tick (in the previous configuration).  If this solves your boot issues I'll disable forced IRQ threading.

**Comment by bubobih** [comment]
thats all info that i can see from kvm... line "nosmt " currently fix and dedi work normal

**Comment by damentz** [comment]
Did you just update from a 5.5 kernel or have you been doing incremental updates?  Just trying to understand if this was caused by a recent change or not.  It seems to me though from what you're saying that it's an outstanding bug in kernel 5.6 that some systems can't boot without `nosmt`.

Do you have a link to the source that says to try `nosmt`?

**Comment by bubobih** [comment]
i use regular update via apt get so i have lates before this one.

**Comment by bubobih** [comment]
I cant now find it i google some error from that page and find that and try it

**Comment by bubobih** [comment]
it latest release same problem, also my hyperthreading is off.... i will recheck bios to see if is bios problem

**Comment by bubobih** [comment]
yap or nosmt or latest kernel disable ht i have only 8 cores.... currently i use old one till u solve it :)

**Comment by damentz** [comment]
The latest kernel I put out yesterday restores periodic tick + tickless idle.  Can you verify if you need `nosmt` to boot?

**Comment by bubobih** [comment]
Yes i need still to use nosmt to boot and he show only 8 threads not 16.

**Comment by damentz** [comment]
Ok, so this sounds like a bug introduced with an upstream stable patch.  I'd say as long as you don't need the extra threads, `nosmt` is fine.  Especially if it's an Intel CPU, every vulnerability that comes out makes SMT less effective.

**Comment by bubobih** [comment]
I use old one i need threads :) no hurry u will fix it some day :)

**Comment by bubobih** [comment]
After your few updates i decide to try again. this is what i can read over kvm

https://i.imgur.com/FpyynYD.jpg
https://i.imgur.com/l8QPlyL.jpg

https://i.imgur.com/eDSpkUG.jpg
https://i.imgur.com/1H0l4rq.jpg

**Comment by mrc4tt** [comment]
Hi, @damentz 

I have a new problem with the booting of AMD Ryzen CPU.

the server is stuck booting of:
**Version: 5.6.0-13.2-liquorix-amd64**

> RDRAND gives funky smelling output, might consider not using it by booting with "nordrand"
![chrome_wGcqWpSrXG](https://user-images.githubusercontent.com/5301047/82325115-f9239380-99da-11ea-9985-54138d9e9889.png)

**Comment by damentz** [comment]
Hi @MikkelDK 

I think you're having two issues.   One is that you may need a bios and/or microcode update to solve the RDRAND issues.  Or you can follow the instructions to disable **nordrand**.

According to this reddit thread, they also recommend installing haveged to force the system to generate entropy: https://www.reddit.com/r/archlinux/comments/f2qhyt/rdrand_gives_funky_smelling_output/

The rdrand check was initially added for buggy rdrand implementations on old AMD systems.  But surprisingly, Ryzen processors are affected too if you have a bad BIOS and/or old microcode version.

As for your system not booting, that may be caused by one of the release candidate patches.  I checked this morning and Greg just dropped "_drm/amdgpu: bump version for invalidate L2 before SDMA IBs_" this morning.  Probably unrelated but considering we don't need the stable patches, I'll just revert them all and spin a new version.

**Comment by mrc4tt** [comment]
Hi @damentz 

Danke! =)
I will do push "update BIOS" or install haveged! =)

**Comment by damentz** [comment]
@MikkelDK how is the latest kernel working on your system, are you able to boot?

@bubobih I disabled Pressure Stall Information framework (CONFIG_PSI).  I saw a report on the CK blog that enabling it caused boot issues a persons system.  Not sure if it's system specific, but can you see if the latest kernel boots correctly without requiring *nosmt*?

**Comment by bubobih** [comment]
same problem....

**Comment by jonathonf** [comment]
Also still having issues with a system running Ubuntu 18.04 on a Ryzen 2700X (with the latest available BIOS).

5.6.0-10.1 boots fine, 5.6.0-10.2 through 5.6.0-13.5 fail to boot.

**Comment by damentz** [comment]
@jonathonf thanks for the feedback, I'm starting to wonder if it's caused by the cgroup options I enabled.

Next release I'll disable the CGROUP options I enabled as part of this thread:

https://techpatterns.com/forums/about2796.html - *Is it possible to enable cgroup-related config?*

It's also important to note, the person who requested these options be enabled wasn't interesting in running Liquorix long term, so I don't think anyone will care if they're turned off again.

**Comment by bubobih** [comment]
i still have same problem with latest one

**Comment by damentz** [comment]
@bubobih the only thing left for me to revert is the actual MuQSS v200 update itself, but this update fixes a lot of time accounting issues that have plagued MuQSS for the longest time.

One thing that did change is the code that detects runqueue sharing.  Can you try booting with `rqshare=mc` or `rqshare=all`?  Also, historically MuQSS has had issues on some systems with less run queues and `rqshare=smt` was required to boot at all.

**Comment by bubobih** [comment]
i didnt try because its pain to request kvm and then broke live full dedi then again fixing it every few days :) i do it few times but customers complain about downtime.... so currently i didnt try what u suggest

**Comment by damentz** [comment]
@bubobih so you didn't try with the change that disabled the PIDS/RDMA cgroups?  I can revert it again but I restored the configuration assuming it didn't change your boot behavior.

Or are you referring to the rqshare boot options?

**Comment by bubobih** [comment]
I didnt try this .

One thing that did change is the code that detects runqueue sharing. Can you try booting with rqshare=mc or rqshare=all? Also, historically MuQSS has had issues on some systems with less run queues and rqshare=smt was required to boot at all

**Comment by bubobih** [comment]
Hello, today i try to use latest kernel again, no any addon its same problem i cant boot...

i even change hardware on datacenter
i set

rqshare=mc  -  nothing same problem
rqshare=all   - nothing same problem

**Comment by bbedward** [comment]
I'm failing to boot as well, ubuntu 20.04 with ryzen 3800x on latest package from PPA.

If you need any more information let me know.

**Comment by thubble** [comment]
I don't use Liquorix but my own custom kernel which includes MuQSS. I have a very similar issue with a hang/error on boot unless I disable forced IRQ threading ("nothreadirqs" on kernel command line). I know this was suggested in an earlier comment but it wasn't clear whether anyone tried it.

**Comment by jonathonf** [comment]
> nothreadirqs

There are a couple of references to this elsewhere.

Firstly, [here](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1274987/comments/19) it appeared to be an issue with USB/EHCI (though that's a low-latency kernel 3.13).

Secondly, with the [ck patchset](http://ck-hack.blogspot.com/2019/05/linux-51-ck1-muqss-version-0192-for.html?showComment=1562567233110#c8738025565005613008) they may have made `nothreadirqs` the default because it can cause issues? Might it be worth asking CK if that's still the case with 5.6-ck2?

**Comment by damentz** [comment]
@jonathonf / @thubble thanks for the feedback.  I'll try disabling forced IRQ threads for the next release.

**Comment by bbedward** [comment]
The latest release resolved the issue for me (5.6-19), works out of the box. Thanks damentz!

**Comment by bubobih** [comment]
I can confirm that finaly this kernel boot :)

**Comment by damentz** [comment]
Great!  Marking as resolved.
