### ISSUE TITLE
linux-headers-4.15.0-5.1-liquorix-* depends on libssl1.1

### ISSUE THREAD

**Issue by z0rc** [damentz/liquorix-package#4]
Probably due to 1e4b80fb52f280b4f7ec9771d87fe89f0ca916ba.

This means that headers cannot be installed on any released Ubuntu version, as libssl1.1 is available only in upcoming 18.04 (bionic) release.

**Comment by damentz** [comment]
Is libssl-dev not the correct meta-package name to cover all releases of Ubuntu?  Per packages.ubuntu.com, libssl-dev goes back to the Trusty release:

https://packages.ubuntu.com/search?keywords=libssl-dev

Also, I find it surprising that there's package compatibility issues, but every supported release of Ubuntu built successfully here: https://launchpad.net/~damentz/+archive/ubuntu/liquorix/+packages. Without marking libssl-dev as a build dependency, all the builds will would have failed.

Can you provide an example of what happens when you try installing the kernel headers?

**Comment by z0rc** [comment]
Oh, I missed those PPA packages entirely and was using main repo which targets Sid. Thanks for pointers. Closing the issue as PPA packages install just fine.
