### ISSUE TITLE
tuned problem

### ISSUE THREAD

**Issue by bubobih** [damentz/liquorix-package#42]
Hello, im notice a problem on this kernel. When im not using tuned tool my cpu temp is 50-55

when i use 

apt-get update
apt-get install tuned tuned-gtk tuned-utils tuned-utils-systemtap

tuned-adm profile latency-performance

my cpu temp is 88c

on another dedi with another kernel there is no change in temperature, and on this one clock is even a bit lower with tuned and i get very high temperature.

Im think that something is not compatibile in this kernel with tuned

**Comment by damentz** [comment]
It's likely that `tuned` is keeping your CPU frequencies higher and keeping you in boost for longer.  This will increase heat output.  Why the change is so dramatic is something you'll have to investigate, unfortunately.

**Comment by bubobih** [comment]
Actualy freq of cpu is lower (fixed) if i can trust of readings. Whitout tuned freq is 4.7 - 4.78. And with tuned its 4.7 fix but cpu goes crazy. I will tonight or in a morning try another kernel and report. But i try on 3 dedi (only 1 have your kernel) and only on that one cpu is crazy. It affect only on 3 tuned profiles connected to latency performance.

**Comment by bubobih** [comment]
xenmax kernel with tuned 


https://i.imgur.com/dnSoEa4.png

**Comment by mabod** [comment]
I have a similar phanomenon with xanmod kernel and with Manjaro kernels and `tuned`. With `tuned` profile "balanced" the CPU temperature is ca. 33 °C. But with profile "latency-performance" it is ca. 44 °C.  I can reliably switch between both profiles and the temperature is going up and down accordingly. But I guess this is more a question for the `tuned` developers rather than kernel developers.
