### ISSUE TITLE
Please package perf tool

### ISSUE THREAD

**Issue by z0rc** [damentz/liquorix-package#5]
Ideally I'd like to have something like linux-tools-liquorix package which integrates with `/usr/bin/perf` wrapper on Ubuntu/Debian. This wrapper helps to automatically select correct perf version depending on current running kernel.

**Comment by damentz** [comment]
Ok, this issue is resolved as of the following commits and kernel builds will be live with the changes shortly after I post and close:

https://github.com/damentz/liquorix-package/commit/a7e83b300a057e967e4b2e30b8461dcb2d70099f -  debian: build perf and add to headers 
https://github.com/damentz/liquorix-package/commit/8bf77099b6c2baacd15f822caebc6120480950f5 -  debian: Add cpupower, turbostat, and x86_energy_perf_policy to headers 
https://github.com/damentz/liquorix-package/commit/006d1742e8adfb5e040da03fe80966358b60a701 -  debian: Use list+loop to copy tools to headers 
https://github.com/damentz/liquorix-package/commit/8d62dd6d60c83581d8d54cdd7e29b6bbd4c8ec76 -  debian: Add profile script to add kernel tools to PATH 

Basically, instead of creating a separate package and wrangling with the differences between Debian and Ubuntu, the kernel tools are built into the kernel headers and a profile script is added to /etc/profile.d/liquorix-tools.sh on every installation.  The profile script tests if the tool binary exists on the running kernel's headers and prepends its folder to `PATH`.  This will make sure that the tools compiled with Liquorix are preferred over what's available on installed system globally.

The only con to this approach is your PATH will get pretty lengthy, but I'm not sure there's away around this without an enormous amount of work creating two separate package types that integrate tightly with Debians and Ubuntus methodology of exposing kernel tools.  Here's an example of what your PATH will look like after installation:

```
$ echo $PATH
/usr/src/linux-headers-5.9.0-12.1-liquorix-amd64/tools/power/x86/x86_energy_perf_policy:/usr/src/linux-headers-5.9.0-12.1-liquorix-amd64/tools/power/x86/turbostat:/usr/src/linux-headers-5.9.0-12.1-liquorix-amd64/tools/power/cpupower:/usr/src/linux-headers-5.9.0-12.1-liquorix-amd64/tools/perf:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/opt/bin
```

**Comment by kroq-gar78** [comment]
When I try to run e.g. `cpupower` with sudo, it picks up the wrong executable since the script in `profile.d` is not run.
```bash
$ sudo cpupower
WARNING: cpupower not found for kernel 5.10.0-9.1

  You may need to install the following packages for this specific kernel:
    linux-tools-5.10.0-9.1-liquorix-amd64
    linux-cloud-tools-5.10.0-9.1-liquorix-amd64

  You may also want to install one of the following packages to keep up to date:
    linux-tools-liquorix-amd64
    linux-cloud-tools-liquorix-amd64

$ sudo sh -c 'echo $PATH'
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

$ sudo which cpupower
/usr/bin/cpupower
```

This PATH is correctly set with `sudo -i` and `sudo su -`. Unfortunately, I'm not knowledgeable enough to know what the best alternative to the `profile.d` script is. I'm on Ubuntu 18.04 with package version `5.10-12ubuntu1~bionic` from the PPA.

**Comment by damentz** [comment]
@kroq-gar78 this is a customization that Canonical configured in Ubuntu to restrict the use of sudo to specific locations.

In your /etc/sudoers, you'll find a line like this: `Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"`

Simply comment it out and sudo will use the PATH of your current user.  This is how sudo is supposed to operate.  Whenever I want a clean environment to run scripts as root, I use `sudo su - ` first.  Looks like Canonical/Ubuntu wants that to happen everytime without your permission rather than let you make that choice.
