### ISSUE TITLE
Intel_pstate not loading in liquorix

### ISSUE THREAD

**Issue by Marc-Pierre-Barbier** [damentz/liquorix-package#51]
im running archlinux and the linux-lqx package from the liquorix repository  https://liquorix.net/archlinux/$repo/$arch
and my system load acpi_cpu instead of loading intel_pstate

**Comment by damentz** [comment]
Yes, that's by design.  Intel's P-State scheduler prefers power consumption over performance and leads to an overall laggy experience on the desktop.  However, if you want to enable `intel_pstate` for the purposes of saving power while using battery, pass `intel_pstate=enable` into your kernel parameters.
