### ISSUE TITLE
ixgbe driver support for 5.11

### ISSUE THREAD

**Issue by ben-burns** [damentz/liquorix-package#55]
Hello,

I'm curious if you only take driver the versions from Zen for drivers such as ixgbe, etc?  I think the ixgbe driver may be out of date for 5.11 kernel support (`ixgbe-5.11.3` adds 5.11 support and was released start of the month), but I figured I would check here before I move over to the Zen project with an issue.

Thanks

**Comment by damentz** [comment]
Yes, this issue should be opened on Zen Kernel and we can take a look there.  If you can close this issue and open the same one there, it'll help to get more eyes.

In the meantime, I did some cursory research and it looks like this _might_ be a doozy to incorporate.  Simply unpacking the latest ixgbe driver[1] over what's in Linux changes the Intel copyright from 2018 to 2021, and generates changes `+23729/-14891`.  Hopefully Intel is keeping their ixgbe kernel updates available through a git repo since integrating this much change is going to be quite a lot of work.

[1] https://sourceforge.net/projects/e1000/files/ixgbe%20stable/5.11.3/

**Comment by ben-burns** [comment]
Thanks @damentz  -- I've opened https://github.com/zen-kernel/zen-kernel/issues/204.  Closing this now.
