### ISSUE TITLE
Only 4 Cpufreq governors available

### ISSUE THREAD

**Issue by RushingAlien** [damentz/liquorix-package#58]
The governors available are
-ondemand
-userspace
-performance 
-schedutil

While on a generic pop os kernel there are
-ondemand
-powersave 
-conservative 
-userspace
-performance 
-schedutil

I don't know if this is intentional or not. if so, please let me know, thanks in advance.

**Comment by damentz** [comment]
Yup that's intentional.  Many distributions are configured to use the 'powersave' governor for intel's p-state cpufreq driver, so when Liquorix defaults to acpi-cpufreq, it sets the maximum frequency to the lowest CPU frequency advertised at boot.  Obviously this is confusing and gives the perception that Liquorix _slows down_ your computer.

To fix this, I just don't build powersave for acpi-cpufreq since almost no one uses it.  You can use the 'userspace' driver and force the frequency to the lowest, or just use your desktop environment's tunables to set the maximum cpu frequency if that matters to you.  TLP and LMT let you do the same thing too.

As for 'conservative', it's just a bad governor overall, I don't even know why it exists.  I wouldn't be surprised if it's removed entirely from mainline some time in the future due to the lack of use.
