### ISSUE TITLE
[Feature Request] support for archlinux32.org and archlinuxarm.org

### ISSUE THREAD

**Issue by shadichy** [damentz/liquorix-package#65]
32bit and arm version plz (even it can be built from the aur with `arch=("i386" "i686" "pentium4" "armv8")` or prebuilt binary )

**Comment by damentz** [comment]
Support for 32-bit was dropped July 2019 due to the outsized ratio of issues to users of the architecture here: https://github.com/damentz/liquorix-package/issues/18.  More reasons for why 32-bit is not worthwhile can be found in the linked forum thread: https://techpatterns.com/forums/about2734.html.  But here's the list so it's easier to find for future reference:

1. Building for 32-bit / 32-bit PAE takes twice the CPU resources to compile than 64-bit

2. The 32-bit / 32-bit PAE kernels take up twice the storage space than 64-bit

3. Per my access log metrics and some data from the Ubuntu PPA, 1 out of 250 users installs a 32-bit kernel

4. Canonical no longer makes 32-bit images to use 32-bit kernels with, you must install an older 32-bit version of Ubuntu and upgrade all the way to the latest

6. Canonical is planning to only support key important 32-bit libraries to support steam and wine

7. Arch, the distribution I run all my kernel builds from doesn't support 32-bit other than multilib libraries, similar to what Canonical is planning

Obviously there's now a 32-bit repo for Arch Linux through the site you mentioned, but like I mentioned before, the effort required to support 32-bit is completely outsized for the number of users.

As for ARM, I'm waiting for a serious daily driver laptop before I spend time on it.  Most use cases of ARM are for servers so Liquorix provides almost no value there.

**Comment by yamaken93** [comment]
@damentz So liquorix does not work and also is not useful for raspberry pi 4? I believe low latency would be useful here since raspberry pi 4 is used for cheap desktops and gaming(specially retro consoles).
