### ISSUE TITLE
Intel Xeon-2245 and Liquorix: Plex limited to 720p streaming, 1080p just doesn't work (Works fine on Xanmod though)

### ISSUE THREAD

**Issue by serialpotato** [damentz/liquorix-package#67]
Hi. I really love liquorix kernel but on my plex server, I cant find direct play or any playback options with 1080p playback. Seems like the kernel is missing modules or libraries necessary for 1080p playback on this particular server? This is because with other kernels like xanmod, I can direct play 1080p resolution and see other 1080p related options which are not available when the server is on liquorix kernel.

The server has XEON-W-2245 Processor and there is no iGPU or an external GPU available. OS is Ubuntu 18.04 LTS. I really wish to just keep using liquorix over xanmod because of performance. Please help

**Comment by damentz** [comment]
I think this is a Plex specific issue.  Searching for "plex force 1080p" online shows that Plex routinely updates their apps and resets remote play settings.

The kernel has nothing to do with what Plex is choosing here, you probably just have a bad timing of updates.

Also, I _HIGHLY_ recommend upgrading your distribution.  Liquorix behaves more strangely the farther you get away from latest upstream.  Latest kernel updates are usually not tested on old userspace so that could be related to what you're seeing.

EDIT: One last thing, transcoding is more expensive than direct stream.  Most likely Plex things your bandwidth can't support 1080p and doesn't make it an option?  Why would it expose a transcode option if that's _more_ expensive for the server?  Lots of questions here, most likely there's a bug in your client app or browser.

**Comment by damentz** [comment]
Closing out this issue, I recommend going to the Plex forums or subreddit and asking this same question there.  Most likely there's some setting you need to flip or change.  Also, if you're not on a paid subscription, GPU acceleration is unavailable.

If you are already on a paid subscription and options disappeared because of missing GPU acceleration, I refer back to my comment that you _NEED_ to upgrade your distribution and use updated GPU drivers.

**Comment by serialpotato** [comment]
> Closing out this issue, I recommend going to the Plex forums or subreddit and asking this same question there. Most likely there's some setting you need to flip or change. Also, if you're not on a paid subscription, GPU acceleration is unavailable.
> 
> If you are already on a paid subscription and options disappeared because of missing GPU acceleration, I refer back to my comment that you _NEED_ to upgrade your distribution and use updated GPU drivers.

I am a paid user. I use exact same configuration and do not change anything when I install xanmod kernel. I also have a KVM VPS, which has the latest liquorix kernel and plex works with 1080p streaming. But liquorix & 1080p Plex just wont work on Xeon W-2245. I am pretty confident there is a missing module, library or something for this processor or server that is holding plex back as the server & network is very powerful in itself.

**Comment by damentz** [comment]
I don't use Plex myself, but I set it up just to see.  After some brief indexing I tried playing a video from my local system and I had full access to all the transcode options and 1080p original streaming itself.

![plex-1080p](https://user-images.githubusercontent.com/284931/134438976-5f89ce38-47b0-4a82-9628-03fe30d19285.png)

This isn't on a KVM VPS but this shows that there's something unique to your system that's causing the issue.

**Comment by damentz** [comment]
Locking this issue, there's not enough information here for me to help you.  The suggestions I gave before still stand:

- Run a much more modern distribution with Liquorix
- Ask for help in the standard support locations, Plex forum and subreddits

Those guys should know enough to help you.
