### ISSUE TITLE
Dependency error when updating

### ISSUE THREAD

**Issue by NoComment1105** [damentz/liquorix-package#74]
Hallo 👋🏼 

I'm updating my kernel to `5.15.0-5.3` but am meeting dependency errors at the end of the update. I can't quite work out what's broken or if the kernel is installed successfully enough for me to be able to restart my system. My error message is bellow

Thanks :)
![image](https://user-images.githubusercontent.com/67918617/143760854-e093dee1-d1d9-475b-9069-b53130412064.png)

**Comment by Auxority** [comment]
I have the same error. Hope this can be fixed soon :)

**Comment by NoComment1105** [comment]
Yikes, at least that means it wasn't something i did to break my system :D

**Comment by Auxority** [comment]
You could try to re-install the base linux kernel, then removing the lqx kernel, reboot your system. Select the base linux kernel, install linux-lqx and linux-lqx-headers again. And reboot. That fixed it for me.
![image](https://user-images.githubusercontent.com/35202343/143763188-07032a5d-dd03-45e6-8f33-a0892d4a5167.png)

**Comment by NoComment1105** [comment]
Interesting, Ill look into doing so, thanks

**Comment by Auxority** [comment]
If you're interested, I am running arch linux.
And these are the command I used:

1) Remove the lqx kernel
```sh
sudo pacman -R linux-lqx-docs linux-lqx-headers linux-lqx
```
2) Install the base linux kernel
```sh
sudo pacman -S linux linux-headers
```
3) Reboot
4) Select the base linux kernel from grub (could be a different bootloader)
5) Edit your pacman.conf
```
sudo nano /etc/pacman/conf
```
6) Add this line to the pacman.conf file
```
[liquorix]
Server = https://liquorix.net/archlinux/$repo/$arch
```
7) Install the lqx kernel
```
sudo pacman -S linux-lqx linux-lqx-headers
```
8) Reboot
9) Select the linux-lqx kernel in your bootloader

That should be it :)

If you encounter issues, you could try running these commands:
Source: https://aur.archlinux.org/packages/linux-lqx/
```
sudo pacman-key --keyserver hkps://keyserver.ubuntu.com --recv-keys 9AE4078033F8024D && sudo pacman-key --lsign-key 9AE4078033F8024D;
```
```
sudo pacman -S coreutils initramfs kmod bc cpio kmod libelf pahole python crda linux-firmware sof-firmware
```

**Comment by NoComment1105** [comment]
Lol using Linux Mint, but im there pretty much

**Comment by NoComment1105** [comment]
Seems that it didn't remove it properly, but it seems to work, This should still be fixed though :)

**Comment by damentz** [comment]
@NoComment1105, are any of your drives full?  The error in your screenshot is that mkinitcpio fails to write to the file system.

You can check with `df -h`.

**Comment by NoComment1105** [comment]
![image](https://user-images.githubusercontent.com/67918617/143780398-01580c74-58d0-4908-bde7-1529992a6d42.png)
Nope no full drives

**Comment by damentz** [comment]
I see, well either way, if you search for `Error 24 : Write error : cannot write compressed block` online, about hundreds of posts return with the problem being not enough space.

I recommend you do two things, remove older kernels (starting with `sudo apt-get autoremove --purge` might help), and changing your default compression from `lz4` (very fast but worst compression), to `xz` (very slow but best compression).

Afterwards, modify your compression in `/etc/initramfs-tools/initramfs.conf` (assuming you're Debian or Ubuntu), and change **COMPRESS=lz4** to **COMPRESS=xz**.  Then run `sudo update-initramfs -k all -c` to recreate all your kernel init ram disks.  Your /boot partition will probably drop from 230M used to about 100M

Closing this issue since it's a system operator problem.  I don't have the ability to manage your boot partition storage for you.

**Comment by NoComment1105** [comment]
Okay Thanks :)
