### ISSUE TITLE
[Suggestion] Restore all available IO schedulers

### ISSUE THREAD

**Issue by DNOX7Mwt22AK** [damentz/liquorix-package#8]
0a85b630e9b1316a9cbb4dbcf37ad47eebe14b98 disabled all non-BFQ schedulers.

However, as of the actual exceedingly active development of BFQ (which includes various untested and experimental ideas, see https://github.com/Algodev-github/bfq-mq/commit/c985e89401e49f17324fe2fcba0e7d06ede58583 amongst other things) I believe this may actually have been in error.

Furthermore, http://ck-hack.blogspot.com/2018/06/linux-417-ck1-muqss-version-0172-for.html

The comment section contains at least 2 people reporting issues with the combination of MuQSS and BFQ. Which may ultimately be traceable back to BFQ itself.

The point being that BFQ is not production ready. Regardless of whether or not it was actually mainlined, it simply is not as reliable on any production system as CFQ is.

I speak from personal experience as well, having been faced with kernel panics in BFQ in recent times. In fact, as recent as yesterday (with the Liquorix kernel). Behaviour which is only exhibited when using BFQ.

It is my belief that it might be preferable to simply allow people to continue using CFQ. BFQ may end up replacing it one day but that is, at best, years into the future.

**Comment by damentz** [comment]
As mentioned in the commit, I disabled all other IO schedulers because distributions were setting alternative IO schedulers that are known to perform worse.  Re-enabling them would reset Liquorix's behavior back to stock on distributions with an opinion on the best IO scheduler for block device type.

Regarding the kernel panics, some of the recent bfq commits actually fixed them.  With some luck I received feedback regarding stability before and after a specific version, 4.17-13 (4.17.0-17.3), and all remaining kernel panics when performing intensive IO activity stopped occurring during a particular rsync run between spinning drives.

Instead of changing IO schedulers, have you tried enabling the blk-mq subsystem?  It's not ready for _all_ systems, but it behaves better (more stability, more performance), when it doesn't have unwanted side effects.

Try adding `scsi_mod.use_blk_mq=y` to your kernel's boot parameters.

**Comment by damentz** [comment]
Closing this out, with distributions able to override less performant IO schedulers with udev, less good IO schedulers will remain disabled to enforce the behavior I'm looking for in Liquorix.
