### ISSUE TITLE
Improvement to repo script

### ISSUE THREAD

**Issue by johnfc2021** [damentz/liquorix-package#86]
I have rewritten the repo script to check to see if the system is x64 and install the kernel headers and image automatically, it also checks whether the distribution is Debian or Ubuntu, and adds the right repo files for that distribution. If there is later support for say CentOS, then an elif section could be added using the yum package manager instead of apt. 

[Edit: Didn't realise that each line needed to be a code or it interprets the lot as text]

```
#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
    echo "[ERROR] You must run this script as root!"
    exit 0
fi

case $(uname -m) in
x86_64)
    ARCH=x64  # or AMD64 or Intel64 or whatever
    ;;
i*86)
    ARCH=x86  # or IA32 or Intel32 or whatever
    # If x86 is not supported then you can simply echo "ERROR: 32 bit not supported" with an exit.
    ;;
*)
    echo "ERROR: Architecture not supported."
    exit
    ;;
esac
dist=$(grep '^ID' /etc/os-release | sed 's/ID=//' | head -1)
if [ $dist = "debian" ]; then
   # Install debian repo
   apt-get install lsb-release -y
   mkdir -p /etc/apt/{sources.list.d,trusted.gpg.d}
   curl -o /etc/apt/trusted.gpg.d/liquorix-keyring.gpg \
    'https://liquorix.net/liquorix-keyring.gpg'
   echo ""
   echo "[INFO ] Liquorix keyring added to /etc/apt/trusted.gpg.d/liquorix-keyring.gpg"
   echo ""
   apt-get install apt-transport-https -y
   repo_file="/etc/apt/sources.list.d/liquorix.list"
   echo "deb http://liquorix.net/debian $codename main
   deb-src http://liquorix.net/debian $codename main

   # Mirrors:
   #
   # Unit193 - France
   # deb http://mirror.unit193.net/liquorix $codename main
   # deb-src http://mirror.unit193.net/liquorix $codename main" > \
    $repo_file
   apt-get update -y

   if [ $ARCH = "x64" ]; then
      sudo apt-get install linux-image-liquorix-amd64 linux-headers-liquorix-amd64 -y
   fi
   echo ""
   echo "[INFO] Liquorix repository added successfully to $repo_file"
   echo ""
elif [$dist = "ubuntu" ]; then
   # Install Ubuntu repo
   echo "Distribution is $dist"
   sudo add-apt-repository ppa:damentz/liquorix && sudo apt-get update
   if [ $ARCH = "x64" ]; then
      sudo apt-get install linux-image-liquorix-amd64 linux-headers-liquorix-amd64 -y
   fi
   echo ""
   echo "[INFO] Liquorix PPA repository added successfully"
   echo ""
# add extra elif's for other supported distributions
else 
    echo "ERROR: This distribution is not supported at this time."
    exit
fi
```

**Comment by damentz** [comment]
I edited your original comment to replace all the per line tickets with two sets of triple ticks so I could read it.

But besides that, this does look somewhat better.  However, I'd prefer a no-code solution completely.  The issue with Debian is there's no equivalent for add-apt-repository as far as I know.  Or maybe you're aware of a way to force add-apt-repository to work with custom repositories outside of Ubuntu?

EDIT: It looks like `add-apt-repository` does support full lines, and this would technically work: `sudo add-apt-repository "deb [arch=amd64] http://liquorix.net/debian bullseye main"`, but it writes it to sources.list instead of sources.list.d/.  Maybe by looking through its source code I can find a way to configure the file name.

EDIT 2: In the python script, you can see the maintainer thought this would be a good idea but couldn't spend 15 minutes to implement it, dooming its use on Debian:

```
    parser = OptionParser(usage)
    # FIXME: provide a --sources-list-file= option that
    #        puts the line into a specific file in sources.list.d
```

I'll keep poking but I think at this point we can't use `add-apt-repository` on Debian without inconveniencing users.

**Comment by damentz** [comment]
Ok, I modified the add-liquorix-repo.sh script to look more like yours with a few modifications.  I also got rid of the mirror that I don't think anyone has tried using.  At this point it's a liability to include it since I don't monitor that site anymore.
