### ISSUE TITLE
Request to correct the full description of Liquorix Linux Kernel 5.18

### ISSUE THREAD

**Issue by mariuszprzeklasa** [damentz/liquorix-package#96]
Request to correct the full description of Liquorix Linux Kernel 5.18 (no digit in the build date and no end bracket)

```
Linux O-PC0683.eservice.local 5.17.0-14.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.17-18.1~bullseye (2022-06-10) x86_64
Linux O-PC0683.eservice.local 5.17.0-15.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.17-19.1~bullseye (2022-06-14) x86_64
```

```
Linux O-PC0683.eservice.local 5.18.0-5.1-liquorix-amd64 #1 ZEN SMP PREEMPT_DYNAMIC liquorix 5.18-1.1~bullseye (2022-06-1 x86_64
Linux O-PC0683.eservice.local 5.18.0-6.1-liquorix-amd64 #1 ZEN SMP PREEMPT_DYNAMIC liquorix 5.18-2.1~bullseye (2022-06-2 x86_64
```

**Comment by damentz** [comment]
@mariuszprzeklasa thanks for the report, next release will use the standard versioning code and not have the erroneous output you included.

**Comment by damentz** [comment]
@mariuszprzeklasa changes had to be reverted, removing any Debian patches breaks the kernel build and install.  The patches included that cause this issue are upstream to Debian itself.  I recommend you report this issue to Debian directly.  I can pull updates from Debian once they fix their patches.

**Comment by mariuszprzeklasa** [comment]
@damentz which Debian GNU/Linux package is causing these problems?

**Comment by damentz** [comment]
@mariuszprzeklasa below are the patches

Upstream Debian: https://salsa.debian.org/kernel-team/linux/-/blob/master/debian/patches/debian/uname-version-timestamp.patch
Downstream Liquorix: https://github.com/damentz/liquorix-package/blob/5.18/master/linux-liquorix/debian/patches/debian/uname-version-timestamp.patch

The patches are resynced on every major updates (5.17 to 5.18, for example), so "fixing" them requires outsized effort on my part.  As I mentioned above, you should see this issue on the stock Debian kernels as well since it's the same patches.
